# Generated by Django 6.0.1 on 2026-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_year',
            field=models.IntegerField(),
        ),
    ]
